// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ---------- //
// hub75_data //
// ---------- //

#define hub75_data_wrap_target 0
#define hub75_data_wrap 2
#define hub75_data_pio_version 1

#define hub75_data_offset_entry_point 0u

static __pio_const uint16_t hub75_data_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0x6006, //  1: out    pins, 6         side 0
    0xb042, //  2: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program hub75_data_program = {
    .instructions = hub75_data_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = hub75_data_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_data_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_data_wrap_target, offset + hub75_data_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// --------- //
// hub75_row //
// --------- //

#define hub75_row_wrap_target 0
#define hub75_row_wrap 10
#define hub75_row_pio_version 1

#define hub75_row_offset_entry_point 0u

static __pio_const uint16_t hub75_row_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6005, //  1: out    pins, 5
    0xe102, //  2: set    pins, 2                [1]
    0xe103, //  3: set    pins, 3                [1]
    0xe002, //  4: set    pins, 2
    0x80a0, //  5: pull   block
    0xa027, //  6: mov    x, osr
    0xe000, //  7: set    pins, 0
    0x0048, //  8: jmp    x--, 8
    0xe002, //  9: set    pins, 2
    0xc000, // 10: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program hub75_row_program = {
    .instructions = hub75_row_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = hub75_row_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_row_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_row_wrap_target, offset + hub75_row_wrap);
    return c;
}
#endif

