// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------------ //
// octal_spi_rx //
// ------------ //

#define octal_spi_rx_wrap_target 0
#define octal_spi_rx_wrap 5
#define octal_spi_rx_pio_version 1

static __pio_const uint16_t octal_spi_rx_program_instructions[] = {
            //     .wrap_target
    0x00c0, //  0: jmp    pin, 0
    0x2028, //  1: wait   0 pin, 8
    0x20a8, //  2: wait   1 pin, 8
    0x4008, //  3: in     pins, 8
    0x00c0, //  4: jmp    pin, 0
    0x0001, //  5: jmp    1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program octal_spi_rx_program = {
    .instructions = octal_spi_rx_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = octal_spi_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config octal_spi_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + octal_spi_rx_wrap_target, offset + octal_spi_rx_wrap);
    return c;
}

/**
 * @brief Initialize the octal_spi_rx PIO program on a state machine.
 *
 * @param pio           PIO instance (pio0 or pio1)
 * @param sm            State machine index
 * @param offset        Program load offset (from pio_add_program)
 * @param data_base_pin First data pin (D0). D0-D7 must be consecutive.
 * @param clk_pin       Clock input pin (must be data_base_pin + 8 for WAIT pin offset)
 * @param cs_pin        Chip select pin (active low, used as JMP pin)
 */
static inline void octal_spi_rx_program_init(PIO pio, uint sm, uint offset,
                                              uint data_base_pin,
                                              uint clk_pin, uint cs_pin) {
    pio_sm_config c = octal_spi_rx_program_get_default_config(offset);
    // IN base = data_base_pin (D0). Pins D0-D7 are sampled by "in pins, 8".
    // CLK is at pin offset 8 from IN base (data_base_pin + 8) for "wait N pin 8".
    sm_config_set_in_pins(&c, data_base_pin);
    // JMP pin = CS (active low). "jmp pin" jumps when CS=1 (high = idle).
    sm_config_set_jmp_pin(&c, cs_pin);
    // IN shift: shift left (MSB first), autopush at 8 bits.
    // Autopush eliminates the need for explicit PUSH in the PIO program.
    sm_config_set_in_shift(&c, false, true, 8);
    // Join FIFOs for deeper RX (8-entry FIFO instead of 4)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // Run PIO at full system clock (150 MHz) for maximum sampling speed.
    // At 80 MHz SPI clock: 150/80 ≈ 1.875 PIO cycles per SPI cycle.
    // The 3-instruction fast path (wait low + wait high + IN) needs ~2 cycles
    // of margin from the WAIT instructions self-syncing to the external clock.
    sm_config_set_clkdiv(&c, 1.0f);
    // Configure GPIO pin functions for PIO
    for (uint i = 0; i < 8; i++) {
        pio_gpio_init(pio, data_base_pin + i);
    }
    pio_gpio_init(pio, clk_pin);
    pio_gpio_init(pio, cs_pin);
    // All pins are inputs
    pio_sm_set_consecutive_pindirs(pio, sm, data_base_pin, 8, false);  // D0-D7 in
    pio_sm_set_pindirs_with_mask(pio, sm, 0,
        (1u << clk_pin) | (1u << cs_pin));  // CLK, CS in
    // Initialize the SM at the program entry point
    pio_sm_init(pio, sm, offset, &c);
    // Start the state machine
    pio_sm_set_enabled(pio, sm, true);
}

#endif

