#!/usr/bin/env python3
# Copyright (c) 2026 ProtoGPU contributors
"""pgl_asset_embed.py — Arduino-oriented embed generation.

Two modes:

  image   Embed a *validated* RAM_HOST firmware image plus its exact
          32-byte PglImageManifest so an Arduino/ESP32 host can upload it
          through PglBootLoader.  The .bin must match the packaging
          manifest (SHA-256, buildId, ABI) — missing, mismatched or
          oversized images fail here, not on the wire.

  asset   Embed any other binary asset (mesh/texture batches, fonts…)
          with the same bounded reader.

Generated <name>.h / <name>.cpp contain plain const byte arrays
(compile-time embed — no runtime text-hex or base64 encoding anywhere)
and a PglChunkReader whose Read() returns at most maxChunk bytes from an
offset: the host streams bounded chunks straight out of its flash and
never needs a full duplicate of the image in RAM.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pgl_image_package import PackageError, validate_manifest



class EmbedError(Exception):
    pass


def _sanitize(name: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        raise EmbedError(f"name {name!r} is not a valid C identifier")
    return name


def _format_array(data: bytes, per_line: int = 12) -> str:
    rows = []
    for i in range(0, len(data), per_line):
        rows.append("    " + ", ".join(f"0x{b:02x}"
                                       for b in data[i:i + per_line]) + ",")
    return "\n".join(rows)


def _write_if_changed(path: str, content: str) -> bool:
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            if fh.read() == content:
                return False
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return True


def generate(name: str, payload: bytes, out_dir: str, chunk: int,
             manifest_bin: bytes | None, meta: dict) -> None:
    sha256 = hashlib.sha256(payload).digest()
    guard = name.upper()
    manifest_decl = ""
    manifest_def = ""
    if manifest_bin is not None:
        manifest_decl = (
            f"\n/* Exact 32-byte PglImageManifest for this image "
            f"(PglBootLoader.h). */\n"
            f"extern const uint8_t {name}_manifest[32];\n")
        manifest_def = (
            f"\nconst uint8_t {name}_manifest[32] = {{\n"
            f"{_format_array(manifest_bin)}\n}};\n")

    meta_comments = "\n".join(
        f" *   {key}: {value}" for key, value in meta.items())
    header = f"""\
/**
 * @file {name}.h — generated by tools/pgl_asset_embed.py
 * Bounded chunk reader over a compile-time embedded payload.
 * The payload lives in the host's flash as a plain const byte array
 * (no text-hex/base64 anywhere); PglChunkRead serves at most
 * {name}_chunk_size bytes per call. PglBootLoader::LoadRamImage can
 * consume {name}_data directly without a full host-RAM duplicate.
 *
 * Payload metadata (verified at generation time):
{meta_comments}
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define {guard}_SIZE {len(payload)}u
#define {guard}_CHUNK_SIZE {chunk}u
#define {guard}_SHA256 "{hashlib.sha256(payload).hexdigest()}"

extern const uint8_t {name}_data[{len(payload)}];
extern const uint8_t {name}_sha256[32];
{manifest_decl}
#ifndef PGL_CHUNK_READER_DEFINED
#define PGL_CHUNK_READER_DEFINED
typedef struct {{
    const uint8_t* data;  /* payload base (host flash) */
    uint32_t size;        /* total payload bytes */
    uint32_t maxChunk;    /* per-read bound */
}} PglChunkReader;
#endif

/* Reader bound to the embedded payload. */
static inline PglChunkReader {name}_reader(void) {{
    PglChunkReader r = {{ {name}_data, {guard}_SIZE, {guard}_CHUNK_SIZE }};
    return r;
}}

/* Bounded read: returns min(request, maxChunk, size - offset) bytes and
 * never touches memory outside the payload; 0 at/past end. */
#ifndef PGL_CHUNK_READ_DEFINED
#define PGL_CHUNK_READ_DEFINED
static inline uint32_t PglChunkRead(const PglChunkReader* reader, uint32_t offset,
                                   uint8_t* dest, uint32_t request) {{
    if (!reader || !reader->data || !dest || offset >= reader->size) return 0;
    uint32_t avail = reader->size - offset;
    uint32_t n = request < reader->maxChunk ? request : reader->maxChunk;
    if (n > avail) n = avail;
    for (uint32_t i = 0; i < n; ++i) dest[i] = reader->data[offset + i];
    return n;
}}
#endif

#ifdef __cplusplus
}}
#endif
"""
    source = f"""\
// Generated by tools/pgl_asset_embed.py — do not edit.
#include "{name}.h"

const uint8_t {name}_data[{len(payload)}] = {{
{_format_array(payload)}
}};

const uint8_t {name}_sha256[32] = {{
{_format_array(sha256)}
}};
{manifest_def}
"""
    wrote_h = _write_if_changed(os.path.join(out_dir, f"{name}.h"), header)
    wrote_c = _write_if_changed(os.path.join(out_dir, f"{name}.cpp"),
                                source)
    state = lambda w: "written" if w else "unchanged"
    print(f"pgl_asset_embed: {name}: {len(payload)} bytes, chunk {chunk}, "
          f"sha256 {hashlib.sha256(payload).hexdigest()[:16]}…")
    print(f"  {os.path.join(out_dir, name + '.h')} ({state(wrote_h)})")
    print(f"  {os.path.join(out_dir, name + '.cpp')} ({state(wrote_c)})")


def mode_image(args: argparse.Namespace) -> int:
    with open(args.bin, "rb") as fh:
        payload = fh.read()
    with open(args.manifest, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)
    expected = validate_manifest(manifest, payload, args.protocol, ram_only=True)
    manifest_bin = expected
    if args.manifest_bin:
        with open(args.manifest_bin, "rb") as fh:
            manifest_bin = fh.read()
        if manifest_bin != expected:
            raise EmbedError("binary manifest differs from validated JSON/image")
    image = manifest["image"]
    padded = image["paddedBytes"]
    meta = {
        "buildId": manifest["build"]["buildIdHex"],
        "profile": manifest["profile"]["bootStorage"],
        "board": manifest["profile"]["board"],
        "protocol": manifest["protocol"]["major"],
        "imageBytes": len(payload),
        "paddedBytes": padded,
        "payloadChecksum": image["payloadChecksum"],
        "flags": manifest["host"]["manifestFlags"],
    }
    generate(_sanitize(args.name), payload, args.out_dir, args.chunk,
             manifest_bin, meta)
    return 0


def mode_asset(args: argparse.Namespace) -> int:
    with open(args.file, "rb") as fh:
        payload = fh.read()
    if not payload:
        raise EmbedError(f"{args.file}: empty asset")
    meta = {
        "sourceFile": os.path.basename(args.file),
        "assetBytes": len(payload),
        "sha256": hashlib.sha256(payload).hexdigest(),
    }
    generate(_sanitize(args.name), payload, args.out_dir, args.chunk,
             None, meta)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate bounded-reader Arduino embeds.")
    sub = ap.add_subparsers(dest="mode", required=True)

    ip = sub.add_parser("image", help="embed a validated firmware image")
    ip.add_argument("--bin", required=True)
    ip.add_argument("--manifest", required=True,
                    help="pgl_image_manifest.json from pgl_image_package.py")
    ip.add_argument("--manifest-bin",
                    help="pgl_image_manifest.bin (else rebuilt from JSON)")
    ip.add_argument("--protocol", type=int, default=9)
    ip.add_argument("--name", required=True)
    ip.add_argument("--out-dir", required=True)
    ip.add_argument("--chunk", type=int, default=4096)

    asp = sub.add_parser("asset", help="embed any binary asset")
    asp.add_argument("--file", required=True)
    asp.add_argument("--name", required=True)
    asp.add_argument("--out-dir", required=True)
    asp.add_argument("--chunk", type=int, default=4096)

    args = ap.parse_args(argv)
    if args.chunk <= 0 or args.chunk > 65536:
        print("pgl_asset_embed: ERROR: --chunk must be in 1..65536",
              file=sys.stderr)
        return 1
    try:
        if args.mode == "image":
            return mode_image(args)
        return mode_asset(args)
    except (EmbedError, PackageError, OSError, json.JSONDecodeError, KeyError) as exc:
        print(f"pgl_asset_embed: ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
