#!/usr/bin/env python3
# Copyright (c) 2026 ProtoGPU contributors
"""pgl_build_identity.py — deterministic firmware build identity.

Hashes the actual compiled inputs (firmware + ProtoGL + ProtoGC working
trees, CMake entry points, dependency lock) plus the build profile into one
digest, and derives a nonzero uint32 buildId from it.  Emits:

  * generated/pgl_build_identity.h   C/C++ macros (PGL_FIRMWARE_BUILD_ID ..)
  * generated/pgl_build_identity.json machine-readable identity record

Determinism rules:
  * repo-relative POSIX paths, sorted; file content hashed, never mtimes
  * no timestamps, hostnames, absolute paths or environment leakage
  * generated/build/git artifacts and the identity outputs themselves are
    excluded, so the hash never depends on its own products (no circular
    self-image hash) and out-of-tree build directories cannot perturb it
  * the same source tree + profile always yields the same buildId; any
    change to compiled code, dependency pins or profile changes it

The firmware compiles PGL_FIRMWARE_BUILD_ID into the image (parent wires
`const uint32_t pgl_build_id = PGL_FIRMWARE_BUILD_ID;` and reports it as
BootInfo.buildId); pgl_image_package.py verifies the compiled value matches
this identity, so the identity provably determines the image value.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

SCHEMA = 1
DEFAULT_PROTOCOL = 9
DEFAULT_BOARD = "PGL-PICO2"

BOOT_STORAGE_IDS = {"RAM_HOST": 1, "FLASH_LOCAL": 2}  # PglRuntime::BootStorage
DISPLAYS = ("SPI", "HUB", "LED", "CUSTOM", "NONE")

SOURCE_DIRS = ("src", "ProtoGL/src", "ProtoGC/src")
EXTRA_FILES = ("CMakeLists.txt", "pico_sdk_import.cmake")

# Excluded from the working-tree hash: generated/build/git artifacts and
# anything that is a build *product* rather than a build *input*.
EXCLUDE_DIR_NAMES = {".git", "__pycache__", "generated", "build", "out"}
EXCLUDE_FILE_NAMES = {"pgl_build_identity.h", "pgl_build_identity.json"}
EXCLUDE_SUFFIXES = (
    ".bak", ".bak2", ".orig", ".rej", ".pyc",
    ".elf", ".bin", ".map", ".uf2", ".hex", ".dis", ".o", ".a", ".obj",
    ".log", ".tmp",
)

HEADER_TEMPLATE = """\
// Generated by tools/pgl_build_identity.py — deterministic build identity.
// Regenerated at build time; do not edit.  Identity inputs: firmware/ProtoGL/
// ProtoGC working trees, dependency lock, toolchain pins, build profile.
#pragma once

#include <stdint.h>

#define PGL_FIRMWARE_BUILD_ID      UINT32_C(0x{build_id:08x})
#define PGL_FIRMWARE_BUILD_ID_HEX  "{build_id:08x}"
#define PGL_PROTOCOL_VERSION       {protocol}u
#define PGL_BUILD_PROFILE          "{boot_storage}"
#define PGL_BOOT_STORAGE           {boot_storage_id}u /* PglRuntime::BootStorage */
#define PGL_BOARD_ID               "{board}"
#define PGL_DEFAULT_DISPLAY        "{display}"
#define PGL_PSRAM_ENABLED          {psram}u
#define PGL_BUILD_CONFIG           "{build_config}"
#define PGL_SOURCE_SHA256          "{source_sha256}"
#define PGL_DEPENDENCY_SHA256      "{dependency_sha256}"
#define PGL_TOOLCHAIN_ID           "{toolchain_id}"

/* Firmware wiring contract: instantiate
 *   const uint32_t pgl_build_id = PGL_FIRMWARE_BUILD_ID;
 * in an accessible translation unit and report BootInfo.buildId from it.
 * pgl_image_package.py verifies the compiled symbol value equals this
 * identity, so the identity determines the image-compiled value. */
"""


class IdentityError(Exception):
    pass


def _hash_file_list(repo: str, rel_files: list[str]) -> tuple[str, dict]:
    """Deterministic hash over sorted relative paths + file bytes."""
    entries = {}
    for rel in sorted(rel_files):
        path = os.path.join(repo, rel)
        with open(path, "rb") as fh:
            data = fh.read()
        entries[rel] = hashlib.sha256(data).hexdigest()
    material = json.dumps(entries, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(material.encode("utf-8")).hexdigest(), entries


def _excluded(rel: str, name: str) -> bool:
    parts = rel.split("/")
    if any(p in EXCLUDE_DIR_NAMES for p in parts[:-1]):
        return True
    if name in EXCLUDE_FILE_NAMES:
        return True
    lower = name.lower()
    return any(lower.endswith(s) for s in EXCLUDE_SUFFIXES)


def collect_source_files(repo: str) -> list[str]:
    rel_files: list[str] = []
    for d in SOURCE_DIRS:
        root = os.path.join(repo, d)
        if not os.path.isdir(root):
            raise IdentityError(f"expected source directory {d} under {repo}")
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(
                x for x in dirnames if x not in EXCLUDE_DIR_NAMES)
            for name in sorted(filenames):
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, repo).replace(os.sep, "/")
                if _excluded(rel, name):
                    continue
                rel_files.append(rel)
    for f in EXTRA_FILES:
        path = os.path.join(repo, f)
        if not os.path.isfile(path):
            raise IdentityError(f"expected build input file {f} under {repo}")
        rel_files.append(f)
    return rel_files


def _write_if_changed(path: str, content: bytes) -> bool:
    if os.path.isfile(path):
        with open(path, "rb") as fh:
            if fh.read() == content:
                return False
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(content)
    return True


def _derive_build_id(digest: bytes) -> int:
    """First u32le of the identity digest; rehashed until nonzero."""
    candidate = digest
    while True:
        value = int.from_bytes(candidate[:4], "little")
        if value:
            return value
        candidate = hashlib.sha256(candidate).digest()


def build_identity(args: argparse.Namespace) -> dict:
    repo = os.path.abspath(args.repo)
    lock_path = os.path.join(repo, args.lock)
    if not os.path.isfile(lock_path):
        raise IdentityError(f"dependency lock not found: {args.lock}")
    with open(lock_path, "rb") as fh:
        lock_bytes = fh.read()
    lock = json.loads(lock_bytes.decode("utf-8"))

    protocol = args.protocol
    lock_protocol = lock.get("protocol_major")
    if lock_protocol is not None and int(lock_protocol) != protocol:
        raise IdentityError(
            f"--protocol {protocol} contradicts lock protocol_major "
            f"{lock_protocol}")

    rel_files = collect_source_files(repo)
    source_sha256, entries = _hash_file_list(repo, rel_files)
    dependency_sha256 = hashlib.sha256(lock_bytes).hexdigest()
    host_sha256, _ = _hash_file_list(
        repo, [p for p in rel_files if p.startswith("ProtoGL/src/")])

    boot_storage_id = BOOT_STORAGE_IDS[args.boot_storage]
    psram_enabled = 1 if args.psram == "ON" else 0
    build_config = (f"{args.boot_storage}+{args.display}+"
                    f"PSRAM_{args.psram}+DIAGNOSTIC_{args.diagnostic}")
    toolchain_id = "arm-none-eabi-gcc " + str(
        lock.get("toolchains", {}).get("arm_gcc", "unknown"))

    material = {
        "schema": SCHEMA,
        "sourceSha256": source_sha256,
        "dependencySha256": dependency_sha256,
        "protocol": protocol,
        "board": args.board,
        "bootStorage": args.boot_storage,
        "display": args.display,
        "psram": bool(psram_enabled),
        "diagnostic": args.diagnostic == "ON",
        "toolchain": toolchain_id,
    }
    material_bytes = json.dumps(material, sort_keys=True,
                                separators=(",", ":")).encode("utf-8")
    identity_digest = hashlib.sha256(material_bytes).digest()
    build_id = _derive_build_id(identity_digest)

    sources_lock = lock.get("sources", {})
    sdk_lock = sources_lock.get("pico_sdk", {})
    identity = {
        "schema": SCHEMA,
        "buildId": build_id,
        "buildIdHex": f"{build_id:08x}",
        "identitySha256": identity_digest.hex(),
        "sourceSha256": source_sha256,
        "hostSourceSha256": host_sha256,
        "dependencySha256": dependency_sha256,
        "protocol": protocol,
        "board": args.board,
        "bootStorage": args.boot_storage,
        "bootStorageId": boot_storage_id,
        "display": args.display,
        "psram": bool(psram_enabled),
        "diagnostic": args.diagnostic == "ON",
        "buildConfig": build_config,
        "toolchain": toolchain_id,
        "sources": {
            "dirs": list(SOURCE_DIRS),
            "extraFiles": list(EXTRA_FILES),
            "fileCount": len(entries),
        },
        "dependencies": {
            "ProtoGL": sources_lock.get("ProtoGL", {}).get("base_commit"),
            "ProtoGC": sources_lock.get("ProtoGC", {}).get("base_commit"),
            "picoSdk": {
                "path": sdk_lock.get("path", "third_party/pico-sdk"),
                "version": sdk_lock.get("version"),
                "commit": sdk_lock.get("commit"),
            },
        },
        "toolchains": lock.get("toolchains", {}),
    }

    header = HEADER_TEMPLATE.format(
        build_id=build_id,
        protocol=protocol,
        boot_storage=args.boot_storage,
        boot_storage_id=boot_storage_id,
        board=args.board,
        display=args.display,
        psram=psram_enabled,
        build_config=build_config,
        source_sha256=source_sha256,
        dependency_sha256=dependency_sha256,
        toolchain_id=toolchain_id,
    )

    wrote_h = _write_if_changed(args.header, header.encode("utf-8"))
    wrote_j = _write_if_changed(
        args.json,
        (json.dumps(identity, indent=2, sort_keys=True) + "\n").encode(
            "utf-8"))
    state = lambda w: "written" if w else "unchanged"
    print(f"pgl_build_identity: buildId=0x{build_id:08x} "
          f"profile={args.boot_storage} display={args.display} "
          f"psram={args.psram} board={args.board} protocol={protocol}")
    print(f"  source sha256   {source_sha256} ({len(entries)} files)")
    print(f"  dependency sha256 {dependency_sha256}")
    print(f"  header {args.header} ({state(wrote_h)})")
    print(f"  json   {args.json} ({state(wrote_j)})")
    return identity


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Deterministic ProtoGPU firmware build identity.")
    ap.add_argument("--repo", default=".", help="repository root")
    ap.add_argument("--boot-storage", required=True,
                    choices=sorted(BOOT_STORAGE_IDS))
    ap.add_argument("--display", required=True, choices=DISPLAYS)
    ap.add_argument("--psram", required=True, choices=("OFF", "ON"))
    ap.add_argument("--diagnostic", default="OFF", choices=("OFF", "ON"))
    ap.add_argument("--board", default=DEFAULT_BOARD)
    ap.add_argument("--protocol", type=int, default=DEFAULT_PROTOCOL)
    ap.add_argument("--lock", default="dependencies.lock.json",
                    help="dependency lock path relative to --repo")
    ap.add_argument("--header", required=True,
                    help="output generated/pgl_build_identity.h")
    ap.add_argument("--json", required=True,
                    help="output generated/pgl_build_identity.json")
    args = ap.parse_args(argv)
    try:
        build_identity(args)
    except (IdentityError, OSError, json.JSONDecodeError) as exc:
        print(f"pgl_build_identity: ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
